### ISSUE TITLE
Too many signals for lifecycle methods on android

### ISSUE THREAD

**Issue by novas1r1** [TelemetryDeck/FlutterSDK#5]
Hey there,
on android I'm getting a lot of signals pushed into my dashboard - around 3k for 3 users in 2 days. Mostly because of lifecycle method calls like "ActivityPaused", "ActivityStopped" etc.

Here's a screenshot showing the signals and user count:
![image](https://github.com/TelemetryDeck/FlutterSDK/assets/2575205/0bb180b8-70a5-4ba3-a9f9-036e5534d9d2)
![image](https://github.com/TelemetryDeck/FlutterSDK/assets/2575205/86805b60-9d3e-4d4b-9f0b-5f31c585f203)

I would like to disable them and only trigger them manually. Would that be possible?

Best
Verry

**Comment by winsmith** [comment]
Hi, thanks so much for this. These signals are configurable with the Kotlin SDK, but the Flutter SDK has no interface to it, so we decided to just not send them for now in #9. New release with this in a minute.
